name: Deploy to InfinityFree

on:
  push:
    branches:
      - Login_setup  # Replace with your actual branch name

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug secrets presence (check if secrets exist)
        run: |
          if [ -z "$FTP_SERVER" ]; then
            echo "❌ FTP_SERVER secret is NOT set"
            exit 1
          else
            echo "✅ FTP_SERVER secret is set"
          fi

          if [ -z "$FTP_USERNAME" ]; then
            echo "❌ FTP_USERNAME secret is NOT set"
            exit 1
          else
            echo "✅ FTP_USERNAME secret is set"
          fi

          if [ -z "$FTP_PASSWORD" ]; then
            echo "❌ FTP_PASSWORD secret is NOT set"
            exit 1
          else
            echo "✅ FTP_PASSWORD secret is set"
          fi

          if [ -z "$FTP_TARGET_DIR" ]; then
            echo "❌ FTP_TARGET_DIR secret is NOT set"
            exit 1
          else
            echo "✅ FTP_TARGET_DIR secret is set"
          fi
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          FTP_TARGET_DIR: ${{ secrets.FTP_TARGET_DIR }}

      - name: Upload to InfinityFree via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_TARGET_DIR }}
          local-dir: .
