name: Deploy to InfinityFree

on:
  push:
    branches:
      - Login_setup  # Your target branch

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug secrets (sanitized output)
        run: |
          echo "Server: ${FTP_SERVER:+✅ SET}"
          echo "Username: ${FTP_USERNAME:+✅ SET}"
          echo "Target Dir: ${FTP_TARGET_DIR:+✅ SET}"
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_TARGET_DIR: ${{ secrets.FTP_TARGET_DIR }}

      - name: Upload to InfinityFree via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftpupload.net
          username: if0_39107441
          password: VipZBKNtfixV
          server-dir: /htdocs/
          local-dir: ./public
